name: Sync labels
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        default: ivyxjc/label-sync

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g github-label-sync

      - name: user repo sync
        if: ${{ startsWith(github.event.inputs.repo, 'ivyxjc') }}
        run: github-label-sync --labels labels.yml ${{github.event.inputs.repo}} --access-token ${{secrets.USER_GITHUB_TOKEN}}
      - name: org CleverCastle repo sync
        if: ${{ startsWith(github.event.inputs.repo, 'clevercastle') }}
        run: github-label-sync --labels labels.yml ${{github.event.inputs.repo}} --access-token ${{secrets.CLEVER_CASTLE_GITHUB_TOKEN}}
